### PR TITLE
WIP: Add support for EPD 3in7

### PR DESCRIPTION
**Pull request by Alexx-G**
Relates to #68 

I've relied on driver implementation for [STM32](https://github.com/waveshare/e-Paper/blob/master/STM32/STM32-F103ZET6/User/e-Paper/EPD_3in7.c) and [RPi](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd3in7.py).

### CODE REVIEW

**Comment by caemor** [comment]
Hey Alexx, 
how is your current status?
greetings,
Chris

**Comment by mangelajo** [comment]
I am preparing an updated PR for this display, as I recently got one looking for a fast-refresh display.

**Comment by mangelajo** [comment]
> I am preparing an updated PR for this display, as I recently got one looking for a fast-refresh display.

Nice I got it working with the latest release. One of the issues seemed to be that the busy signal reading was inverted.

I have also verified that the Box::new(Displayxxx:default()) approach works, I'll document that in a separate PR too.

@caemor I guess that based on previous discussions the approach for 4-gray/1-gray is having 2 different versions of the display driver, right?

**Comment by peckpeck** [comment]
Is it of any use having a B/W only version ? Is it any faster ?
If no a simple 4 gray implementation should be enough

**Comment by mangelajo** [comment]
I have posted the PR here https://github.com/caemor/epd-waveshare/pull/129

We could close this PR at this point, original authorship is retained in the commit

**Comment by mangelajo** [comment]
> Is it of any use having a B/W only version ? Is it any faster ? If no a simple 4 gray implementation should be enough

Memory usage is half, for 4 grayscale it doesn't work in ESP32C3 as far as I checked.

I will do timing checks , and try to factor-out common parts across 4gray/BW.

**Comment by peckpeck** [comment]
i think esp32c3 has enough memory, but i understand the argument

**Pull request closed without merging**
