### PR TITLE
WIP: Epd2in66 module

### PR DESCRIPTION
**Pull request by Lite5h4dow**
this is not the final version. just wan to get this here so you can take a look and advise on any further changes, stuck on the rotation functions atm.

### CODE REVIEW

**Comment by Lite5h4dow** [comment]
i cant test the b/w/r model so im just gonna commit this if thats ok?

**Comment by Lite5h4dow** [comment]
i cant test the b/w/r model so im just gonna commit this if thats ok?

**Comment by Lite5h4dow** [comment]
i havent yet, it dosent work just yet its still throwing some errors

**Comment by Lite5h4dow** [comment]
Sorry, haven't had the time to get back to this, I will at some point though

**Comment by caemor** [comment]
Resolved in #147

**Pull request closed without merging**
